# Docker Compose for Production Deployment (split FE/BE)

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: booking-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      # If you keep CORS on the backend:
      # - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      # These are build-time values consumed by Vite. They must be provided via
      # the shell env, a project .env file, or `--env-file`. They are baked into the bundle.
      args:
        VITE_API_URL: "${VITE_API_URL:-/api}"
        VITE_SUPABASE_URL: "${VITE_SUPABASE_URL:?VITE_SUPABASE_URL is required (set in .env or pass with --env-file)}"
        VITE_SUPABASE_ANON_KEY: "${VITE_SUPABASE_ANON_KEY:?VITE_SUPABASE_ANON_KEY is required (set in .env or pass with --env-file)}"
    container_name: booking-frontend
    ports:
      - "80:80"       # Frontend on 80
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge