# Docker Compose for Local Development Testing
# Use this for testing OAuth flows locally

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: "${VITE_SUPABASE_URL}"
        VITE_SUPABASE_ANON_KEY: "${VITE_SUPABASE_ANON_KEY}"
        VITE_API_URL: "${VITE_API_URL:-http://localhost:3000}"
    ports:
      - "80:3001"    # Frontend on port 80
      - "3000:3000"  # Backend API on port 3000
    env_file:
      - .env.production
    environment:
      - NODE_ENV=development
      # Override the site URL for local OAuth testing
      - SUPABASE_SITE_URL=http://localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
