create table "public"."test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test" enable row level security;

alter table "public"."booking_items" alter column "provider_organization_id" set not null;

CREATE UNIQUE INDEX test_pkey ON public.test USING btree (id);

alter table "public"."test" add constraint "test_pkey" PRIMARY KEY using index "test_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_item_availability()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  RAISE WARNING 'Trigger fired function: update_item_availability. Operation: %', TG_OP;

  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    RAISE WARNING 'NEW.status: %, OLD.status: %', NEW.status, OLD.status;

    IF NEW.status = 'picked_up' AND (OLD.status IS DISTINCT FROM 'picked_up') THEN
      RAISE WARNING 'Confirmed item. Subtracting quantity % from item_id %', NEW.quantity, NEW.item_id;

      UPDATE storage_items
      SET available_quantity = available_quantity - NEW.quantity
      WHERE id = NEW.item_id AND available_quantity >= NEW.quantity;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'Not enough available items for storage item %', NEW.item_id;
      END IF;
    END IF;

    IF NEW.status = 'returned' AND (OLD.status IS DISTINCT FROM 'returned') THEN
      RAISE WARNING 'Cancelled item. Adding quantity % back to item_id %', NEW.quantity, NEW.item_id;

      UPDATE storage_items
      SET available_quantity = available_quantity + NEW.quantity
      WHERE id = NEW.item_id;
    END IF;

  ELSIF TG_OP = 'DELETE' THEN
    RAISE WARNING 'Deleted item. Adding quantity % back to item_id %', OLD.quantity, OLD.item_id;

    UPDATE storage_items
    SET available_quantity = available_quantity + OLD.quantity
    WHERE id = OLD.item_id;
  END IF;

  RETURN COALESCE(NEW, OLD);

EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING 'Trigger error: %', SQLERRM;
    RETURN NULL;
END;
$function$
;

grant delete on table "public"."audit_logs" to "anon";

grant insert on table "public"."audit_logs" to "anon";

grant references on table "public"."audit_logs" to "anon";

grant select on table "public"."audit_logs" to "anon";

grant trigger on table "public"."audit_logs" to "anon";

grant truncate on table "public"."audit_logs" to "anon";

grant update on table "public"."audit_logs" to "anon";

grant delete on table "public"."audit_logs" to "authenticated";

grant insert on table "public"."audit_logs" to "authenticated";

grant references on table "public"."audit_logs" to "authenticated";

grant select on table "public"."audit_logs" to "authenticated";

grant trigger on table "public"."audit_logs" to "authenticated";

grant truncate on table "public"."audit_logs" to "authenticated";

grant update on table "public"."audit_logs" to "authenticated";

grant delete on table "public"."audit_logs" to "service_role";

grant insert on table "public"."audit_logs" to "service_role";

grant references on table "public"."audit_logs" to "service_role";

grant select on table "public"."audit_logs" to "service_role";

grant trigger on table "public"."audit_logs" to "service_role";

grant truncate on table "public"."audit_logs" to "service_role";

grant update on table "public"."audit_logs" to "service_role";

grant delete on table "public"."booking_items" to "anon";

grant insert on table "public"."booking_items" to "anon";

grant references on table "public"."booking_items" to "anon";

grant select on table "public"."booking_items" to "anon";

grant trigger on table "public"."booking_items" to "anon";

grant truncate on table "public"."booking_items" to "anon";

grant update on table "public"."booking_items" to "anon";

grant delete on table "public"."booking_items" to "authenticated";

grant insert on table "public"."booking_items" to "authenticated";

grant references on table "public"."booking_items" to "authenticated";

grant select on table "public"."booking_items" to "authenticated";

grant trigger on table "public"."booking_items" to "authenticated";

grant truncate on table "public"."booking_items" to "authenticated";

grant update on table "public"."booking_items" to "authenticated";

grant delete on table "public"."booking_items" to "service_role";

grant insert on table "public"."booking_items" to "service_role";

grant references on table "public"."booking_items" to "service_role";

grant select on table "public"."booking_items" to "service_role";

grant trigger on table "public"."booking_items" to "service_role";

grant truncate on table "public"."booking_items" to "service_role";

grant update on table "public"."booking_items" to "service_role";

grant delete on table "public"."bookings" to "anon";

grant insert on table "public"."bookings" to "anon";

grant references on table "public"."bookings" to "anon";

grant select on table "public"."bookings" to "anon";

grant trigger on table "public"."bookings" to "anon";

grant truncate on table "public"."bookings" to "anon";

grant update on table "public"."bookings" to "anon";

grant delete on table "public"."bookings" to "authenticated";

grant insert on table "public"."bookings" to "authenticated";

grant references on table "public"."bookings" to "authenticated";

grant select on table "public"."bookings" to "authenticated";

grant trigger on table "public"."bookings" to "authenticated";

grant truncate on table "public"."bookings" to "authenticated";

grant update on table "public"."bookings" to "authenticated";

grant delete on table "public"."bookings" to "service_role";

grant insert on table "public"."bookings" to "service_role";

grant references on table "public"."bookings" to "service_role";

grant select on table "public"."bookings" to "service_role";

grant trigger on table "public"."bookings" to "service_role";

grant truncate on table "public"."bookings" to "service_role";

grant update on table "public"."bookings" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."organization_locations" to "anon";

grant insert on table "public"."organization_locations" to "anon";

grant references on table "public"."organization_locations" to "anon";

grant select on table "public"."organization_locations" to "anon";

grant trigger on table "public"."organization_locations" to "anon";

grant truncate on table "public"."organization_locations" to "anon";

grant update on table "public"."organization_locations" to "anon";

grant delete on table "public"."organization_locations" to "authenticated";

grant insert on table "public"."organization_locations" to "authenticated";

grant references on table "public"."organization_locations" to "authenticated";

grant select on table "public"."organization_locations" to "authenticated";

grant trigger on table "public"."organization_locations" to "authenticated";

grant truncate on table "public"."organization_locations" to "authenticated";

grant update on table "public"."organization_locations" to "authenticated";

grant delete on table "public"."organization_locations" to "service_role";

grant insert on table "public"."organization_locations" to "service_role";

grant references on table "public"."organization_locations" to "service_role";

grant select on table "public"."organization_locations" to "service_role";

grant trigger on table "public"."organization_locations" to "service_role";

grant truncate on table "public"."organization_locations" to "service_role";

grant update on table "public"."organization_locations" to "service_role";

grant delete on table "public"."organizations" to "anon";

grant insert on table "public"."organizations" to "anon";

grant references on table "public"."organizations" to "anon";

grant select on table "public"."organizations" to "anon";

grant trigger on table "public"."organizations" to "anon";

grant truncate on table "public"."organizations" to "anon";

grant update on table "public"."organizations" to "anon";

grant delete on table "public"."organizations" to "authenticated";

grant insert on table "public"."organizations" to "authenticated";

grant references on table "public"."organizations" to "authenticated";

grant select on table "public"."organizations" to "authenticated";

grant trigger on table "public"."organizations" to "authenticated";

grant truncate on table "public"."organizations" to "authenticated";

grant update on table "public"."organizations" to "authenticated";

grant delete on table "public"."organizations" to "service_role";

grant insert on table "public"."organizations" to "service_role";

grant references on table "public"."organizations" to "service_role";

grant select on table "public"."organizations" to "service_role";

grant trigger on table "public"."organizations" to "service_role";

grant truncate on table "public"."organizations" to "service_role";

grant update on table "public"."organizations" to "service_role";

grant select on table "public"."organizations" to "supabase_auth_admin";

grant delete on table "public"."promotions" to "anon";

grant insert on table "public"."promotions" to "anon";

grant references on table "public"."promotions" to "anon";

grant select on table "public"."promotions" to "anon";

grant trigger on table "public"."promotions" to "anon";

grant truncate on table "public"."promotions" to "anon";

grant update on table "public"."promotions" to "anon";

grant delete on table "public"."promotions" to "authenticated";

grant insert on table "public"."promotions" to "authenticated";

grant references on table "public"."promotions" to "authenticated";

grant select on table "public"."promotions" to "authenticated";

grant trigger on table "public"."promotions" to "authenticated";

grant truncate on table "public"."promotions" to "authenticated";

grant update on table "public"."promotions" to "authenticated";

grant delete on table "public"."promotions" to "service_role";

grant insert on table "public"."promotions" to "service_role";

grant references on table "public"."promotions" to "service_role";

grant select on table "public"."promotions" to "service_role";

grant trigger on table "public"."promotions" to "service_role";

grant truncate on table "public"."promotions" to "service_role";

grant update on table "public"."promotions" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "supabase_auth_admin";

grant delete on table "public"."storage_analytics" to "anon";

grant insert on table "public"."storage_analytics" to "anon";

grant references on table "public"."storage_analytics" to "anon";

grant select on table "public"."storage_analytics" to "anon";

grant trigger on table "public"."storage_analytics" to "anon";

grant truncate on table "public"."storage_analytics" to "anon";

grant update on table "public"."storage_analytics" to "anon";

grant delete on table "public"."storage_analytics" to "authenticated";

grant insert on table "public"."storage_analytics" to "authenticated";

grant references on table "public"."storage_analytics" to "authenticated";

grant select on table "public"."storage_analytics" to "authenticated";

grant trigger on table "public"."storage_analytics" to "authenticated";

grant truncate on table "public"."storage_analytics" to "authenticated";

grant update on table "public"."storage_analytics" to "authenticated";

grant delete on table "public"."storage_analytics" to "service_role";

grant insert on table "public"."storage_analytics" to "service_role";

grant references on table "public"."storage_analytics" to "service_role";

grant select on table "public"."storage_analytics" to "service_role";

grant trigger on table "public"."storage_analytics" to "service_role";

grant truncate on table "public"."storage_analytics" to "service_role";

grant update on table "public"."storage_analytics" to "service_role";

grant delete on table "public"."storage_compartments" to "anon";

grant insert on table "public"."storage_compartments" to "anon";

grant references on table "public"."storage_compartments" to "anon";

grant select on table "public"."storage_compartments" to "anon";

grant trigger on table "public"."storage_compartments" to "anon";

grant truncate on table "public"."storage_compartments" to "anon";

grant update on table "public"."storage_compartments" to "anon";

grant delete on table "public"."storage_compartments" to "authenticated";

grant insert on table "public"."storage_compartments" to "authenticated";

grant references on table "public"."storage_compartments" to "authenticated";

grant select on table "public"."storage_compartments" to "authenticated";

grant trigger on table "public"."storage_compartments" to "authenticated";

grant truncate on table "public"."storage_compartments" to "authenticated";

grant update on table "public"."storage_compartments" to "authenticated";

grant delete on table "public"."storage_compartments" to "service_role";

grant insert on table "public"."storage_compartments" to "service_role";

grant references on table "public"."storage_compartments" to "service_role";

grant select on table "public"."storage_compartments" to "service_role";

grant trigger on table "public"."storage_compartments" to "service_role";

grant truncate on table "public"."storage_compartments" to "service_role";

grant update on table "public"."storage_compartments" to "service_role";

grant delete on table "public"."storage_images" to "anon";

grant insert on table "public"."storage_images" to "anon";

grant references on table "public"."storage_images" to "anon";

grant select on table "public"."storage_images" to "anon";

grant trigger on table "public"."storage_images" to "anon";

grant truncate on table "public"."storage_images" to "anon";

grant update on table "public"."storage_images" to "anon";

grant delete on table "public"."storage_images" to "authenticated";

grant insert on table "public"."storage_images" to "authenticated";

grant references on table "public"."storage_images" to "authenticated";

grant select on table "public"."storage_images" to "authenticated";

grant trigger on table "public"."storage_images" to "authenticated";

grant truncate on table "public"."storage_images" to "authenticated";

grant update on table "public"."storage_images" to "authenticated";

grant delete on table "public"."storage_images" to "service_role";

grant insert on table "public"."storage_images" to "service_role";

grant references on table "public"."storage_images" to "service_role";

grant select on table "public"."storage_images" to "service_role";

grant trigger on table "public"."storage_images" to "service_role";

grant truncate on table "public"."storage_images" to "service_role";

grant update on table "public"."storage_images" to "service_role";

grant delete on table "public"."storage_item_images" to "anon";

grant insert on table "public"."storage_item_images" to "anon";

grant references on table "public"."storage_item_images" to "anon";

grant select on table "public"."storage_item_images" to "anon";

grant trigger on table "public"."storage_item_images" to "anon";

grant truncate on table "public"."storage_item_images" to "anon";

grant update on table "public"."storage_item_images" to "anon";

grant delete on table "public"."storage_item_images" to "authenticated";

grant insert on table "public"."storage_item_images" to "authenticated";

grant references on table "public"."storage_item_images" to "authenticated";

grant select on table "public"."storage_item_images" to "authenticated";

grant trigger on table "public"."storage_item_images" to "authenticated";

grant truncate on table "public"."storage_item_images" to "authenticated";

grant update on table "public"."storage_item_images" to "authenticated";

grant delete on table "public"."storage_item_images" to "service_role";

grant insert on table "public"."storage_item_images" to "service_role";

grant references on table "public"."storage_item_images" to "service_role";

grant select on table "public"."storage_item_images" to "service_role";

grant trigger on table "public"."storage_item_images" to "service_role";

grant truncate on table "public"."storage_item_images" to "service_role";

grant update on table "public"."storage_item_images" to "service_role";

grant delete on table "public"."storage_item_tags" to "anon";

grant insert on table "public"."storage_item_tags" to "anon";

grant references on table "public"."storage_item_tags" to "anon";

grant select on table "public"."storage_item_tags" to "anon";

grant trigger on table "public"."storage_item_tags" to "anon";

grant truncate on table "public"."storage_item_tags" to "anon";

grant update on table "public"."storage_item_tags" to "anon";

grant delete on table "public"."storage_item_tags" to "authenticated";

grant insert on table "public"."storage_item_tags" to "authenticated";

grant references on table "public"."storage_item_tags" to "authenticated";

grant select on table "public"."storage_item_tags" to "authenticated";

grant trigger on table "public"."storage_item_tags" to "authenticated";

grant truncate on table "public"."storage_item_tags" to "authenticated";

grant update on table "public"."storage_item_tags" to "authenticated";

grant delete on table "public"."storage_item_tags" to "service_role";

grant insert on table "public"."storage_item_tags" to "service_role";

grant references on table "public"."storage_item_tags" to "service_role";

grant select on table "public"."storage_item_tags" to "service_role";

grant trigger on table "public"."storage_item_tags" to "service_role";

grant truncate on table "public"."storage_item_tags" to "service_role";

grant update on table "public"."storage_item_tags" to "service_role";

grant delete on table "public"."storage_items" to "anon";

grant insert on table "public"."storage_items" to "anon";

grant references on table "public"."storage_items" to "anon";

grant select on table "public"."storage_items" to "anon";

grant trigger on table "public"."storage_items" to "anon";

grant truncate on table "public"."storage_items" to "anon";

grant update on table "public"."storage_items" to "anon";

grant delete on table "public"."storage_items" to "authenticated";

grant insert on table "public"."storage_items" to "authenticated";

grant references on table "public"."storage_items" to "authenticated";

grant select on table "public"."storage_items" to "authenticated";

grant trigger on table "public"."storage_items" to "authenticated";

grant truncate on table "public"."storage_items" to "authenticated";

grant update on table "public"."storage_items" to "authenticated";

grant delete on table "public"."storage_items" to "service_role";

grant insert on table "public"."storage_items" to "service_role";

grant references on table "public"."storage_items" to "service_role";

grant select on table "public"."storage_items" to "service_role";

grant trigger on table "public"."storage_items" to "service_role";

grant truncate on table "public"."storage_items" to "service_role";

grant update on table "public"."storage_items" to "service_role";

grant delete on table "public"."storage_locations" to "anon";

grant insert on table "public"."storage_locations" to "anon";

grant references on table "public"."storage_locations" to "anon";

grant select on table "public"."storage_locations" to "anon";

grant trigger on table "public"."storage_locations" to "anon";

grant truncate on table "public"."storage_locations" to "anon";

grant update on table "public"."storage_locations" to "anon";

grant delete on table "public"."storage_locations" to "authenticated";

grant insert on table "public"."storage_locations" to "authenticated";

grant references on table "public"."storage_locations" to "authenticated";

grant select on table "public"."storage_locations" to "authenticated";

grant trigger on table "public"."storage_locations" to "authenticated";

grant truncate on table "public"."storage_locations" to "authenticated";

grant update on table "public"."storage_locations" to "authenticated";

grant delete on table "public"."storage_locations" to "service_role";

grant insert on table "public"."storage_locations" to "service_role";

grant references on table "public"."storage_locations" to "service_role";

grant select on table "public"."storage_locations" to "service_role";

grant trigger on table "public"."storage_locations" to "service_role";

grant truncate on table "public"."storage_locations" to "service_role";

grant update on table "public"."storage_locations" to "service_role";

grant delete on table "public"."storage_working_hours" to "anon";

grant insert on table "public"."storage_working_hours" to "anon";

grant references on table "public"."storage_working_hours" to "anon";

grant select on table "public"."storage_working_hours" to "anon";

grant trigger on table "public"."storage_working_hours" to "anon";

grant truncate on table "public"."storage_working_hours" to "anon";

grant update on table "public"."storage_working_hours" to "anon";

grant delete on table "public"."storage_working_hours" to "authenticated";

grant insert on table "public"."storage_working_hours" to "authenticated";

grant references on table "public"."storage_working_hours" to "authenticated";

grant select on table "public"."storage_working_hours" to "authenticated";

grant trigger on table "public"."storage_working_hours" to "authenticated";

grant truncate on table "public"."storage_working_hours" to "authenticated";

grant update on table "public"."storage_working_hours" to "authenticated";

grant delete on table "public"."storage_working_hours" to "service_role";

grant insert on table "public"."storage_working_hours" to "service_role";

grant references on table "public"."storage_working_hours" to "service_role";

grant select on table "public"."storage_working_hours" to "service_role";

grant trigger on table "public"."storage_working_hours" to "service_role";

grant truncate on table "public"."storage_working_hours" to "service_role";

grant update on table "public"."storage_working_hours" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";

grant delete on table "public"."test" to "anon";

grant insert on table "public"."test" to "anon";

grant references on table "public"."test" to "anon";

grant select on table "public"."test" to "anon";

grant trigger on table "public"."test" to "anon";

grant truncate on table "public"."test" to "anon";

grant update on table "public"."test" to "anon";

grant delete on table "public"."test" to "authenticated";

grant insert on table "public"."test" to "authenticated";

grant references on table "public"."test" to "authenticated";

grant select on table "public"."test" to "authenticated";

grant trigger on table "public"."test" to "authenticated";

grant truncate on table "public"."test" to "authenticated";

grant update on table "public"."test" to "authenticated";

grant delete on table "public"."test" to "service_role";

grant insert on table "public"."test" to "service_role";

grant references on table "public"."test" to "service_role";

grant select on table "public"."test" to "service_role";

grant trigger on table "public"."test" to "service_role";

grant truncate on table "public"."test" to "service_role";

grant update on table "public"."test" to "service_role";

grant delete on table "public"."test_features" to "anon";

grant insert on table "public"."test_features" to "anon";

grant references on table "public"."test_features" to "anon";

grant select on table "public"."test_features" to "anon";

grant trigger on table "public"."test_features" to "anon";

grant truncate on table "public"."test_features" to "anon";

grant update on table "public"."test_features" to "anon";

grant delete on table "public"."test_features" to "authenticated";

grant insert on table "public"."test_features" to "authenticated";

grant references on table "public"."test_features" to "authenticated";

grant select on table "public"."test_features" to "authenticated";

grant trigger on table "public"."test_features" to "authenticated";

grant truncate on table "public"."test_features" to "authenticated";

grant update on table "public"."test_features" to "authenticated";

grant delete on table "public"."test_features" to "service_role";

grant insert on table "public"."test_features" to "service_role";

grant references on table "public"."test_features" to "service_role";

grant select on table "public"."test_features" to "service_role";

grant trigger on table "public"."test_features" to "service_role";

grant truncate on table "public"."test_features" to "service_role";

grant update on table "public"."test_features" to "service_role";

grant delete on table "public"."user_addresses" to "anon";

grant insert on table "public"."user_addresses" to "anon";

grant references on table "public"."user_addresses" to "anon";

grant select on table "public"."user_addresses" to "anon";

grant trigger on table "public"."user_addresses" to "anon";

grant truncate on table "public"."user_addresses" to "anon";

grant update on table "public"."user_addresses" to "anon";

grant delete on table "public"."user_addresses" to "authenticated";

grant insert on table "public"."user_addresses" to "authenticated";

grant references on table "public"."user_addresses" to "authenticated";

grant select on table "public"."user_addresses" to "authenticated";

grant trigger on table "public"."user_addresses" to "authenticated";

grant truncate on table "public"."user_addresses" to "authenticated";

grant update on table "public"."user_addresses" to "authenticated";

grant delete on table "public"."user_addresses" to "service_role";

grant insert on table "public"."user_addresses" to "service_role";

grant references on table "public"."user_addresses" to "service_role";

grant select on table "public"."user_addresses" to "service_role";

grant trigger on table "public"."user_addresses" to "service_role";

grant truncate on table "public"."user_addresses" to "service_role";

grant update on table "public"."user_addresses" to "service_role";

grant delete on table "public"."user_ban_history" to "anon";

grant insert on table "public"."user_ban_history" to "anon";

grant references on table "public"."user_ban_history" to "anon";

grant select on table "public"."user_ban_history" to "anon";

grant trigger on table "public"."user_ban_history" to "anon";

grant truncate on table "public"."user_ban_history" to "anon";

grant update on table "public"."user_ban_history" to "anon";

grant delete on table "public"."user_ban_history" to "authenticated";

grant insert on table "public"."user_ban_history" to "authenticated";

grant references on table "public"."user_ban_history" to "authenticated";

grant select on table "public"."user_ban_history" to "authenticated";

grant trigger on table "public"."user_ban_history" to "authenticated";

grant truncate on table "public"."user_ban_history" to "authenticated";

grant update on table "public"."user_ban_history" to "authenticated";

grant delete on table "public"."user_ban_history" to "service_role";

grant insert on table "public"."user_ban_history" to "service_role";

grant references on table "public"."user_ban_history" to "service_role";

grant select on table "public"."user_ban_history" to "service_role";

grant trigger on table "public"."user_ban_history" to "service_role";

grant truncate on table "public"."user_ban_history" to "service_role";

grant update on table "public"."user_ban_history" to "service_role";

grant delete on table "public"."user_organization_roles" to "anon";

grant insert on table "public"."user_organization_roles" to "anon";

grant references on table "public"."user_organization_roles" to "anon";

grant select on table "public"."user_organization_roles" to "anon";

grant trigger on table "public"."user_organization_roles" to "anon";

grant truncate on table "public"."user_organization_roles" to "anon";

grant update on table "public"."user_organization_roles" to "anon";

grant delete on table "public"."user_organization_roles" to "authenticated";

grant insert on table "public"."user_organization_roles" to "authenticated";

grant references on table "public"."user_organization_roles" to "authenticated";

grant select on table "public"."user_organization_roles" to "authenticated";

grant trigger on table "public"."user_organization_roles" to "authenticated";

grant truncate on table "public"."user_organization_roles" to "authenticated";

grant update on table "public"."user_organization_roles" to "authenticated";

grant delete on table "public"."user_organization_roles" to "service_role";

grant insert on table "public"."user_organization_roles" to "service_role";

grant references on table "public"."user_organization_roles" to "service_role";

grant select on table "public"."user_organization_roles" to "service_role";

grant trigger on table "public"."user_organization_roles" to "service_role";

grant truncate on table "public"."user_organization_roles" to "service_role";

grant update on table "public"."user_organization_roles" to "service_role";

grant select on table "public"."user_organization_roles" to "supabase_auth_admin";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";


