name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deployment
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deployment

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install common dependencies (common types folder)
        run: |
          cd common
          npm ci
      - name: Create environment file
        run: |
          cd frontend
          echo "VITE_SUPABASE_URL=https://rcbddkhvysexkvgqpcud.supabase.co" > .env.production
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.production
          echo "VITE_API_URL=https://booking-app-backend-duh9encbeme0awca.northeurope-01.azurewebsites.net" >> .env.production
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_GRASS_049DC8010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          app_build_command: "npm run build" # Explicitly define build command
          ###### End of Repository/Build Configurations ######
      - name: Verify Environment Variables
        run: |
          cd frontend
          echo "Checking environment variables for troubleshooting:"
          echo "VITE_SUPABASE_URL length: ${#VITE_SUPABASE_URL}"
          echo "VITE_SUPABASE_ANON_KEY available: $(if [ -n "$VITE_SUPABASE_ANON_KEY" ]; then echo "Yes"; else echo "No"; fi)"
          echo "VITE_API_URL available: $(if [ -n "$VITE_API_URL" ]; then echo "Yes"; else echo "No"; fi)"
        env:
          VITE_SUPABASE_URL: "https://rcbddkhvysexkvgqpcud.supabase.co" ###### hardcoded for debugging purposes ######
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VITE_API_URL: https://booking-app-backend-duh9encbeme0awca.northeurope-01.azurewebsites.net

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_GRASS_049DC8010 }}
          action: "close"
